<?php

namespace forum\PlatformBundle\Repository;

/**
 * membreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class membreRepository extends \Doctrine\ORM\EntityRepository
{
}
