<?php

namespace forum\PlatformBundle\Repository;

/**
 * sectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sectionRepository extends \Doctrine\ORM\EntityRepository
{
}
