<?php

namespace forum\PlatformBundle\Repository;

/**
 * topicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class topicRepository extends \Doctrine\ORM\EntityRepository
{
}
